### ISSUE TITLE
xmlstarlet completion in zsh 5.5

### ISSUE THREAD

**Issue by okapia** [hejack0207/zsh-xml-plugin#1]
Have you seen https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_xmlstarlet

That's included in the zsh 5.5 release.

**Comment by hejack0207** [comment]
I add wrapper function for xmlstarlet command to get better auto completions user experience, and it was adapted from the zsh version. By now it's only for my personal usage.
